networks:
  frontend-network:
    driver: bridge

volumes:
  nginx_logs:
  ssl_certs:
  certbot_www:
  letsencrypt_data:

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://seurasaeng.site/api
        DOMAIN: seurasaeng.site
        EMAIL: admin@seurasaeng.site
    image: seuraseung-frontend:latest
    container_name: seuraseung-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend-network
    volumes:
      - nginx_logs:/var/log/nginx
      - ssl_certs:/etc/ssl
      - certbot_www:/var/www/certbot
      - letsencrypt_data:/etc/letsencrypt
    environment:
      - DOMAIN=seurasaeng.site
      - EMAIL=admin@seurasaeng.site
      - AUTO_SSL=true
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f https://localhost/health -k || curl -f http://localhost/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 45s