networks:
  frontend-network:
    driver: bridge

volumes:
  nginx_logs:
    driver: local
  ssl_certs:
    driver: local
  certbot_www:
    driver: local

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://seurasaeng.site/api
        DOMAIN: seurasaeng.site
        EMAIL: admin@seurasaeng.site
    image: seuraseung-frontend:latest
    container_name: seuraseung-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend-network
    volumes:
      - nginx_logs:/var/log/nginx
      - /home/ubuntu/logs/nginx:/var/log/nginx
      - ssl_certs:/etc/ssl
      - certbot_www:/var/www/certbot
    environment:
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_WORKER_CONNECTIONS=1024
      - DOMAIN=seurasaeng.site
      - EMAIL=admin@seurasaeng.site
      - AUTO_SSL=true
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f https://localhost/health -k || curl -f http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "com.docker.compose.service=frontend"
      - "com.seuraseung.service=frontend"
      - "com.seuraseung.version=2.0.0"

  # SSL 자동 갱신 (선택사항)
  ssl-renewer:
    image: seuraseung-frontend:latest
    container_name: seuraseung-ssl-renewer
    restart: unless-stopped
    volumes:
      - ssl_certs:/etc/ssl
      - certbot_www:/var/www/certbot
    environment:
      - DOMAIN=seurasaeng.site
      - EMAIL=admin@seurasaeng.site
    command: ["/scripts/ssl-renewal.sh", "daemon"]
    networks:
      - frontend-network
    depends_on:
      - frontend
    profiles:
      - ssl-renewal